from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^$', 'tickets.texas.views.index'),
    (r'^view/(?P<event_id>\d+)/$', 'tickets.texas.views.view_event'),
    (r'^index.html$', 'tickets.texas.views.index'),
    (r'^about/$', 'tickets.texas.views.about'),
    (r'^test/$', 'tickets.texas.views.test'),
    (r'^contact/$', 'tickets.texas.views.contact'),
    (r'^terms/$', 'tickets.texas.views.terms'),
    (r'^buy/$', 'tickets.texas.views.buy'),
    (r'^buy/(?P<occurrence_id>\d+)/$', 'tickets.texas.views.buy_occurrence'),
    (r'^buy/requests/$', 'tickets.texas.views.requests'),
    (r'^buy/purchases/$', 'tickets.texas.views.purchases'),
    (r'^buy/purchases/pay/(?P<purchase_id>\d+)/$',
        'tickets.texas.views.purchase_pay'),
    (r'^buy/purchases/receipt/(?P<purchase_id>\d+)/$',
        'tickets.texas.views.purchase_receipt'),
    (r'^buy/purchases/print/(?P<purchase_id>\d+)/$',
        'tickets.texas.views.purchase_print'),
    (r'^buy/paypal_return/$', 'tickets.texas.views.paypal_return'),
    (r'^buy/paypal_cancel/$', 'tickets.texas.views.paypal_cancel'),
    (r'^buy/paypal_process/(?P<purchase_id>\d+)/$',
        'tickets.texas.views.paypal_process'),
    (r'^buy/amazon_process/$', 'tickets.texas.views.amazon_process'),
    (r'^buy/amazon_cancel/$', 'tickets.texas.views.amazon_cancel'),
    (r'^buy/amazon_instantpaymentnotification/$',
        'tickets.texas.views.amazon_ipn'),

    (r'^chance/(?P<tier_id>\d+)/$', 'tickets.texas.views.chance_tier'),

    (r'^tickets/$', 'tickets.texas.views.tickets'),
    (r'^tickets/print/(?P<ticket_id>\d+)/$',
        'tickets.texas.views.ticket_print'),
    (r'^tickets/waiver/(?P<ticket_id>\d+)/$',
        'tickets.texas.views.ticket_waiver'),

    (r'^donate/thanks/$', 'tickets.texas.views.donate_thanks'),
    (r'^donate/ohwell/$', 'tickets.texas.views.donate_ohwell'),
    (r'^donate/instantpaymentnotification/$',
        'tickets.texas.views.donate_instantpaymentnotification'),

    (r'^events/(?P<event_id>\d+)/admin/$', 'tickets.texas.views.event_admin'),
    (r'^occurrences/(?P<occurrence_id>\d+)/admin/ticket_list/$',
        'tickets.texas.views.occurrence_admin_ticket_list'),
    (r'^occurrences/(?P<occurrence_id>\d+)/admin/ticket_stats/$',
        'tickets.texas.views.occurrence_admin_ticket_stats'),
    (r'^occurrences/(?P<occurrence_id>\d+)/admin/ticket_export/$',
        'tickets.texas.views.occurrence_admin_ticket_export'),
    (r'^occurrences/(?P<occurrence_id>\d+)/admin/sale/$',
        'tickets.texas.views.occurrence_admin_sale'),
    (r'^occurrences/(?P<occurrence_id>\d+)/admin/option_list/$',
        'tickets.texas.views.occurrence_admin_option_list'),

    (r'^profile/$', 'tickets.texas.views.user_profile'),
    (r'^login/$', 'tickets.texas.views.user_login'),
    (r'^confirm/(?P<user_id>\d+)/(?P<code>.+)/$',
        'tickets.texas.views.user_confirm'),
    (r'^logout/$', 'tickets.texas.views.user_logout'),
    (r'^password_change/$', 'django.contrib.auth.views.password_change'),
    (r'^password_change_done/$',
        'django.contrib.auth.views.password_change_done'),
)
